name: Deploy
on:
  workflow_run:
    workflows: [TestApplication]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Stop service
        run: echo 'Should stop the docker server'

      - name: Push code
        run: echo 'Should push the code'

      - name: Start service
        run: echo 'Should stop the docker service'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test of secret sharing app failed, check the result in original step'
