name: DeploySecretSharing
on:
  workflow_run:
    workflows: [TestApplication]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_HETZNER }} 
          known_hosts: ${{ secrets.APP_HOST_HETZNER }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.APP_HOST_HETZNER }} >> ~/.ssh/known_hosts

      - name: Stop service
        run: ssh root@${{ secrets.APP_HOST_HETZNER }} "cd /var/www/secret_app/app; docker-compose down"

      - name: Push code
        run: rsync -az --chown=www-data:www-data ${{ github.workspace }} root@${{ secrets.APP_HOST }}:/var/www/secret_app

      - name: Build image
        run: ssh root@${{ secrets.APP_HOST_HETZNER }} "cd /var/www/secret_app/app; docker-compose build"

      - name: Start service
        run: ssh root@${{ secrets.APP_HOST_HETZNER }} "cd /var/www/secret_app/app; docker-compose up -d"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test of secret sharing app failed, check result.xml in test step'