name: Deploy
on:
  workflow_run:
    workflows: [TestApplication]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop service
        run: echo 'Should stop the docker server'
        run: ssh root@${{ secrets.SSH_HOST }} "cd /var/www/secret_app/app; docker-compose down"

      - name: Push code
        run: rsync -az --progress --stats --chown=www-data:www-data ${{ github.workspace }} root@{{ secrets.SSH_HOST }}:/var/www/secret_app

      - name: Build image
        run: ssh root@${{ secrets.SSH_HOST }} "cd /var/www/secret_app/app; docker-compose build"

      - name: Start service
        run: ssh root@${{ secrets.SSH_HOST }} "cd /var/www/secret_app/app; docker-compose up -d"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test of secret sharing app failed, check the result in original step'

# name: Publish to live server
# on:
#   push:
#     branches: [ 'releases/**' ]
# jobs:
#   package:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#       - name: Fill in templates
#         run: |
#           sed 's/\[\[DATABASE_PASSWORD\]\]/${{ secrets.DABASEPASSWORD }}/' ${{ github.workspace }}/templates/config.php.inc > ${{ github.workspace }}/new/config/config.php.inc

      # - name: publish
      #   run: |
      #     rsync -avzh --delete-after --chown=www-data:www-data  ${{ github.workspace }}/new/. root@${{ secrets.SSH_HOST }}:/var/www/gratissiden_v2/html