name: PyTest
on: push






jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ${GITHUB_WORKSPACE}/app/Dockerfile --tag test-secret
    
    - name: Test
      run: |
        working-directory: app
        docker run -v ${GITHUB_WORKSPACE}/app:/App test-secret pytest